//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakery.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BakeryAzureEntities : DbContext
    {
        public BakeryAzureEntities()
            : base("name=BakeryAzureEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accesory> Accesories { get; set; }
        public virtual DbSet<Additive> Additives { get; set; }
        public virtual DbSet<Adress> Adresses { get; set; }
        public virtual DbSet<CakeCreator> CakeCreators { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Cream> Creams { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Filling> Fillings { get; set; }
        public virtual DbSet<FinishedOrder> FinishedOrders { get; set; }
        public virtual DbSet<Finish> Finishes { get; set; }
        public virtual DbSet<Icing> Icings { get; set; }
        public virtual DbSet<Level> Levels { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Shape> Shapes { get; set; }
        public virtual DbSet<SpongeCake> SpongeCakes { get; set; }
        public virtual DbSet<ShoppingCart> ShoppingCarts { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
