//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CakeCreator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CakeCreator()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int CakeCreatorID { get; set; }
        public Nullable<int> ShapeID { get; set; }
        public Nullable<int> LevelID { get; set; }
        public Nullable<int> SpongeCakeID { get; set; }
        public Nullable<int> CreamID { get; set; }
        public Nullable<int> FillingID { get; set; }
        public Nullable<int> IcingID { get; set; }
        public Nullable<int> FinishID { get; set; }
        public Nullable<int> AdditionID { get; set; }
        public Nullable<int> AccesoryID { get; set; }
    
        public virtual Accesory Accesory { get; set; }
        public virtual Additive Additive { get; set; }
        public virtual Cream Cream { get; set; }
        public virtual Filling Filling { get; set; }
        public virtual Finish Finish { get; set; }
        public virtual Icing Icing { get; set; }
        public virtual Level Level { get; set; }
        public virtual Shape Shape { get; set; }
        public virtual SpongeCake SpongeCake { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
